#Config for TradeOntime

#オンタイムチケットのMythicMobsにおけるアイテム名。空白の場合オンタイムポイントをオンタイムチケットに変換できなくなります。
MythicMobsItemName: ontime_ticket

#オンタイムチケットをMythicMobsではなくコマンドで配布する場合 true
UseCommandForOntimeItem: false

#オンタイムチケットの表示名。文字コードは&a形式ではなく§a形式で記入してね。
MythicMobsDisplayName: §aオンタイムチケット

#変換時にチケット一枚が何ポイントになるかの数値。
PointsPerTicket: 10