name: TradeOntime
version: ${project.version}
main: com.github.mori01231.tradeontime.TradeOntime
description: Trade ontime for items

commands:
  tradeontime:
    description: オンタイムポイントをオンタイムチケットに変換する
    permission: tradeontime.tradeontime
    usage: /tradeontime ポイント数 でオンタイムポイントをオンタイムチケットに変換できます

permissions:
  tradeontime.*:
    description: 全tradeontimeコマンドへのアクセス権限
    children:
      tradeontime.tradeontime: true
  tradeontime.tradeontime:
    description: オンタイムポイントをオンタイムチケットに変換することが可能になる。
    default: true