name: TradeOntime
version: ${project.version}
main: com.github.mori01231.tradeontime.TradeOntime
description: Trade ontime for items
depend: [PlayerPoints]

commands:
  ontimetoticket:
    description: オンタイムポイントをオンタイムチケットに変換する
    aliases: [ott]
    permission: tradeontime.ontimetoticket
    usage: 例：/ott ポイント数
  tickettoontime:
    description: 所持している全チケットをオンタイムポイントに変換する。
    aliases: [tto]
    permission: tradeontime.tickettoontime
    usage: 例：/tto

permissions:
  tradeontime.*:
    description: 全tradeontimeコマンドへのアクセス権限
    children:
      tradeontime.ontimetoticket: true
      tradeontime.tickettoontime: true
  tradeontime.ontimetoticket:
    description: オンタイムポイントをオンタイムチケットに変換することが可能になる。
    default: true
  tradeontime.tickettoontime:
    description: オンタイムチケットをオンタイムポイントに変換することが可能になる。
    default: true